version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - apt-get update -y
      - apt-get install -y r-base r-base-dev
      - Rscript -e 'install.packages("pkgdown")'

  build:
    commands:
      - echo Build started on `date`
      - Rscript -e 'pkgdown::build_site()'

  post_build:
    commands:
     - aws s3 sync --delete ./docs s3://exploristics.theme

cache:
  paths:
  - /root/.cache/pip
