#' @title Add a footer with the Exploristics logo to a ggplot2 figure.
#' @description This function returns a ggplot with a footer with the Exploristics logo and an optional text caption added below the plot.
#' @details This function returns a ggplot with a footer with the Exploristics logo at the bottom-right corner and an optional text caption at the bottom-left corner below the plot.
#' There is also an option to add a line between the plot and the footer.
#' The image file can be generated by creating a plot the running `ggsave()` with a filename specified.
#' The plot with the footer added is saved to a .png file with the same filename as the original plot but with the suffix "with_footer" added to it.
#' @param filename An image file of a ggplot2.
#' @param text Optional text to add to the left of the footer. Single line or across 2 lines if you add `\n` between the lines of text.
#' @param line Add a line between the plot and the footer. Defaults to `FALSE`.
#' @param logo Path to an image file to use in the footer. The path must be URL, filename or raw vector. Defaults uses the Exploristics logo supplied with the package.
#' @param suffix Suffix to add to the original plot filename. Don't need to include file extension. Defaults to "_with_footer".
#' @seealso \code{\link[magick]{image_read}}
#' @seealso \code{\link[magick]{image_trim}}
#' @seealso \code{\link[magick]{image_scale}}
#' @seealso \code{\link[magick]{image_background}}
#' @seealso \code{\link[magick]{image_extent}}
#' @seealso \code{\link[magick]{image_border}}
#' @seealso \code{\link[magick]{image_annotate}}
#' @seealso \code{\link[magick]{image_info}}
#' @seealso \code{\link[magick]{image_blank}}
#' @seealso \code{\link[magick]{image_append}}
#' @seealso \code{\link[magick]{image_write}}
#' @import 'ggplot2'
#' @import 'magick'
#' @import 'magrittr'
#' @importFrom tools file_path_sans_ext
#' @export
#' @examples
#' library(ggplot2)
#' library(magick)
#' library(magrittr)
#' library(scales)
#' library(stringr)
#'
#' ## generate a plot with the Exploristics theme
#' cars_plot <- ggplot(data = mtcars, aes(x = hp, y = mpg, colour = mpg)) +
#' geom_point(size=2) +
#' labs(title="Example plot") +
#' exploristics_theme()
#'
#' ## add colour scheme and wrap text labels
#' cars_plot %>%
#' exploristics_colour(colour_pal="Expl_External") %>%
#' text_wrapper()
#'
#' ## save the plot
#' ggsave(filename = "example_cars_plot.png", width = 8, height = 8, dpi = 300)
#'
#' ## add the footer to the saved plot
#' add_footer("example_cars_plot.png", text= "Source:Data source\nProduced by: Name")



add_footer <- function(filename=NULL,text=NULL,line=FALSE,logo=NULL,suffix=NULL){

  if(is.null(filename)){
    stop("No file provided. Please enter a filename.")
  } else{
    # read in the plot
    plot <- image_read(filename)

    # get plot info
    plot_info <- image_info(plot)

    if(is.null(logo)){
      # read in the logo
      logo_raw = image_read(system.file("extdata","FC_logo_only_name.png", package="ExploristicsTheme"))
    } else{
      logo_raw = image_read(logo)
    }


    # calculate the scaling needed for the logo based on the dimensions of the plot
    # square
    scale_logo_num <- round(plot_info$height*0.125,0)
    scale_extent_num <- paste0(round(plot_info$height/1.846,0),"x75")#, round(plot_info$height/32,0))

    # long
    if(plot_info$height > plot_info$width){
      scale_logo_num <- round(plot_info$width*0.125,0)
      scale_extent_num <- paste0(round(plot_info$width/1.846,0),"x75")#, round(plot_info$height/32,0))

    }
    # wide
    if(plot_info$height < plot_info$width){
      scale_logo_num <- round(plot_info$height*0.125,0)
      scale_extent_num <- paste0(round(plot_info$width/1.846,0),"x75")#, round(plot_info$height/32,0))
    }

    # scale down the logo and give it a border so it's on the right side of the footer
    footer <- logo_raw %>%
      image_trim()%>%
      image_scale("300") %>%
      image_background("white", flatten = TRUE) %>% # #A2D7E4
      image_extent(scale_extent_num, gravity="east",color = "white") %>%
      image_border("10x10",color = "white")

    # if text caption is to be added, put it on the left side of the footer
    if(is.null(text)==FALSE){
      if(grepl("\n",text)==TRUE){
        footer <- footer %>%
          image_annotate(text, color = "#2D2669", size = 25,
                         location = "+10+15", gravity = "northwest")
      } else{
        footer <- footer %>%
          image_annotate(text, color = "#2D2669", size = 25,
                         location = "+10+25", gravity = "northwest")
      }

    }

    # if using a line between the plot and footer, create it
    if(isTRUE(line)){
      # new image to act as a line break
      # make it the same length as the footer
      lb_width <- image_info(footer)$width
      lb_height <- 3
      lb <- image_blank(lb_width, lb_height, color = "#2D2669")

      # set final plot dimensions to the same as the original plot
      final_dim <- paste0(plot_info$width,"x",plot_info$height)

      # stack the 3 images (plot, line, footer) on top of each other
      final_plot <- image_append(image_scale(c(plot,lb, footer), final_dim), stack = TRUE)
    } else{

      # set final plot dimensions to the same as the original plot
      final_dim <- paste0(plot_info$width,"x",plot_info$height)

      # stack the 2 images (plot, footer) on top of each other
      final_plot <- image_append(image_scale(c(plot, footer), final_dim), stack = TRUE)
    }


    if(is.null(suffix)){
      # save the plot with the footer added
      image_write(final_plot, paste0(tools::file_path_sans_ext(filename),"_with_footer.png"))

    } else{
      # save the plot with the footer added
      image_write(final_plot, paste0(tools::file_path_sans_ext(filename),suffix, ".png"))

    }

  }



}
